/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author User
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFormPersediaan = new javax.swing.JButton();
        btnFormJenis = new javax.swing.JButton();
        btnFormObatMasuk = new javax.swing.JButton();
        btnFormObatKeluar = new javax.swing.JButton();
        btnFormAdmin = new javax.swing.JButton();
        btnFormPegawai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistem Informasi Apotek");

        btnFormPersediaan.setText("Form Persediaan Obat");
        btnFormPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPersediaanActionPerformed(evt);
            }
        });

        btnFormJenis.setText("Form Jenis Obat");
        btnFormJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormJenisActionPerformed(evt);
            }
        });

        btnFormObatMasuk.setText("Form Obat Masuk");
        btnFormObatMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormObatMasukActionPerformed(evt);
            }
        });

        btnFormObatKeluar.setText("Form Obat Keluar");
        btnFormObatKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormObatKeluarActionPerformed(evt);
            }
        });

        btnFormAdmin.setText("Form Admin");
        btnFormAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormAdminActionPerformed(evt);
            }
        });

        btnFormPegawai.setText("Form Pegawai");
        btnFormPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPegawaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFormObatMasuk)
                    .addComponent(btnFormObatKeluar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormJenis)
                            .addComponent(btnFormPersediaan))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormPegawai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFormAdmin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFormJenis, btnFormObatKeluar, btnFormObatMasuk, btnFormPersediaan});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFormAdmin, btnFormPegawai});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormPersediaan)
                    .addComponent(btnFormAdmin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormJenis)
                    .addComponent(btnFormPegawai))
                .addGap(18, 18, 18)
                .addComponent(btnFormObatMasuk)
                .addGap(18, 18, 18)
                .addComponent(btnFormObatKeluar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPersediaanActionPerformed
        // TODO add your handling code here:
        new framePersediaan().setVisible(true);
    }//GEN-LAST:event_btnFormPersediaanActionPerformed

    private void btnFormJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormJenisActionPerformed
        // TODO add your handling code here:
        new frameJenis().setVisible(true);
    }//GEN-LAST:event_btnFormJenisActionPerformed

    private void btnFormObatMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormObatMasukActionPerformed
        // TODO add your handling code here:
        new frameObatMasuk().setVisible(true);
    }//GEN-LAST:event_btnFormObatMasukActionPerformed

    private void btnFormObatKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormObatKeluarActionPerformed
        // TODO add your handling code here:
        new frameObatKeluar().setVisible(true);
    }//GEN-LAST:event_btnFormObatKeluarActionPerformed

    private void btnFormAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormAdminActionPerformed
        // TODO add your handling code here:
        new frameAdmin().setVisible(true);
    }//GEN-LAST:event_btnFormAdminActionPerformed

    private void btnFormPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPegawaiActionPerformed
        // TODO add your handling code here:
        new framePegawai().setVisible(true);
    }//GEN-LAST:event_btnFormPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormAdmin;
    private javax.swing.JButton btnFormJenis;
    private javax.swing.JButton btnFormObatKeluar;
    private javax.swing.JButton btnFormObatMasuk;
    private javax.swing.JButton btnFormPegawai;
    private javax.swing.JButton btnFormPersediaan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
